# Generated by Django 4.1.6 on 2023-05-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sancionatorios',
            fields=[
                ('expediente', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RazonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_sanionatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarea2.sancionatorios')),
            ],
        ),
        migrations.CreateModel(
            name='Fiscalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('id_sanionatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarea2.sancionatorios')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_sanionatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarea2.sancionatorios')),
            ],
        ),
    ]
